"""Export run-level paired-delta statistics for application-case Appendix tables."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "RL_MACPO_IEEE_English_with_images" / "media" / "application_appendix_stats.tex"

SCENARIOS = [
    ("MAED-13", ROOT / "power_dispatch_sim/output/maed_20260701_175417/MAED13/summary.json"),
    ("Resource scheduling", ROOT / "power_dispatch_sim/output/paper_20260701_175627/RESOURCE/summary.json"),
    ("EV dispatch", ROOT / "power_dispatch_sim/output/paper_20260701_175627/EVDISPATCH/summary.json"),
    ("IEEE-30", ROOT / "power_dispatch_sim/output/power_IEEE30_20260630_114805/summary.json"),
    ("IEEE-57", ROOT / "power_dispatch_sim/output/power_IEEE57_20260630_114810/summary.json"),
    ("IEEE-118", ROOT / "power_dispatch_sim/output/power_IEEE118_20260701_175246/summary.json"),
]


def paired_delta_pct(summary_path: Path) -> tuple[np.ndarray, float]:
    j = json.loads(summary_path.read_text(encoding="utf-8"))
    rows = j["rows"]
    m = np.array([r["best_f_pure"] for r in rows if r.get("algorithm") == "MACPO"], dtype=float)
    r = np.array([r["best_f_pure"] for r in rows if r.get("algorithm") == "RL-MACPO"], dtype=float)
    delta = (m - r) / np.abs(m) * 100.0
    comm = float(j["RL-MACPO"]["comm_rate_mean"])
    return delta, comm


def fmt_pct(x: float) -> str:
    return f"{x:+.1f}" if abs(x) >= 0.05 else "0.0"


def main() -> None:
    lines = [
        "% Auto-generated by utils/application_appendix_stats.py",
        "\\begin{table*}[!t]",
        "\\centering",
        "\\scriptsize",
        "\\caption{Run-level paired cost-gap statistics on dispatch and IEEE pilots "
        "($\\Delta=(\\mathrm{MACPO}-\\mathrm{RL})/|\\mathrm{MACPO}|\\times100\\%$. "
        "Positive $\\Delta$ favors RL-MACPO.) RL comm.\\ is mean RL-MACPO trigger rate.}",
        "\\label{tab:application_run_stats}",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "Scenario & Runs & Median $\\Delta$ (\\%) & Q1--Q3 (\\%) & Min--Max (\\%) & RL comm. \\\\",
        "\\midrule",
    ]
    for name, path in SCENARIOS:
        if not path.is_file():
            raise FileNotFoundError(path)
        delta, comm = paired_delta_pct(path)
        q1, med, q3 = np.percentile(delta, [25, 50, 75])
        lines.append(
            f"{name} & {len(delta)} & {fmt_pct(med)} & "
            f"[{fmt_pct(q1)}, {fmt_pct(q3)}] & "
            f"[{fmt_pct(delta.min())}, {fmt_pct(delta.max())}] & "
            f"{comm * 100:.1f}\\% \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "}",
            "\\end{table*}",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
